# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    #agrega hostname para poder ingresar desde adminer
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dw
    ports:
      - 5432:5432

  adminer:
    image: adminer
    hostname: adminer
    container_name: m5_db_1
    restart: always
    ports:
      - 8080:8080